baseURL = 'https://jurogrammer.github.io/blog/'
languageCode = 'en-us'
title = 'Jurogrammer blog'
theme = 'PaperMod'
      
[params.assets]
  disableHLJS = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[markup]
  [markup.highlight]
    noClasses = true
    style = "dracula"
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
    codeFences = true
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

[params]
  math = true
  mainSections = ["languages", "library-and-frameworks", "testing", "general", "cs", "architecture"]

[menu]

[[menu.main]]
identifier = "Languages"
name = "Languages"
url = "/languages/"
weight = 1

[[menu.main]]
identifier = "LibraryFramework"
name = "Library & Framework"
url = "/library-and-frameworks/"
weight = 1

[[menu.main]]
identifier = "Architecture"
name = "Architecture"
url = "/architecture"
weight = 1

[[menu.main]]
identifier = "CS"
name = "CS"
url = "/cs"
weight = 1

[[menu.main]]
identifier = "Testing"
name = "Testing"
url = "/testing"
weight = 1


[[menu.main]]
identifier = "General"
name = "General"
url = "/general"
weight = 1

[[menu.main]]
identifier = "Tools"
name = "Tools"
url = "/tools/"
weight = 1


[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"
